server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://mysql-sciman:3306/sciman
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
